-- ==============================================================================
-- 🚀 TROCÔ: FREE TIER REGISTRATION TRIGGER (V3 - FINAL)
-- ==============================================================================
-- ⚠️ DESCUBRIMOS: A coluna `password` na tabela `usuarios` é NOT NULL!
-- Como ela é obrigatória, o banco dava Erro 500 porque a gente estava inserindo
-- um usuário sem mandar a senha.
-- 
-- SOLUÇÃO: Pegamos a senha encriptada que o Supabase acabou de gerar e
-- salvamos nessa coluna obrigatória.
-- ==============================================================================

-- 1. Create a secure function to handle the new user insertion
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.usuarios (email, nome, password, tem_plano)
  VALUES (
    NEW.email,
    -- Extract full_name from the raw_user_meta_data JSON if available
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    -- NEW.encrypted_password holds the secure hash generated by Supabase Auth
    NEW.encrypted_password,
    false -- default to Free Tier
  )
  ON CONFLICT (email) DO NOTHING;
  
  RETURN NEW;
END;
$$;

-- 2. Create/Replace the trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==============================================================================
-- ✅ DONE: Now, whenever a user completes the "Criar Conta Grátis", they will
-- immediately and securely be added to the users table with tem_plano = false!
-- E agora com a COLUNA PASSWORD PREENCHIDA!
-- ==============================================================================
