-- 1. Create a table to store Credit Cards
create table if not exists public.credit_cards (
  id bigint generated by default as identity primary key,
  user_id bigint references public.usuarios(id) not null,
  name text not null,
  limit_amount numeric not null default 0,
  closing_day integer not null check (closing_day >= 1 and closing_day <= 31),
  due_day integer not null check (due_day >= 1 and due_day <= 31),
  color text not null default '#10B981', -- Hex color code
  brand text, -- Visa, Mastercard, etc. (optional)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.credit_cards enable row level security;

-- Policies for credit_cards
create policy "Users can view their own cards"
  on public.credit_cards for select
  using (user_id = (select id from public.usuarios where email = auth.email())); 

create policy "Users can insert their own cards"
  on public.credit_cards for insert
  with check (true);

create policy "Users can update their own cards"
  on public.credit_cards for update
  using (true);

create policy "Users can delete their own cards"
  on public.credit_cards for delete
  using (true);

-- Index for credit_cards
create index if not exists credit_cards_user_id_idx on public.credit_cards (user_id);


-- 2. Add card_id column to transacoes table
-- We check if the column exists first to avoid errors if re-running (optional but good practice, though 'alter table add column' naturally fails if exists unless using 'if not exists' in newer PG versions or just letting it fail if manual)
-- For simplicity in Supabase API, we just run the add column. If it fails because it exists, that's fine for manual runs, but let's assume this is the definitive script.

alter table public.transacoes
add column if not exists card_id bigint references public.credit_cards(id) on delete set null;

-- Add index for performance on transacoes
create index if not exists transacoes_card_id_idx on public.transacoes(card_id);
